// env.d.ts
declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_RAPIDAPI_KEY: string;
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: string;
    NEXT_RESEND_API_KEY: string;
    NEXT_WEB_URL: string;
    NEXT_API_STRAPI_URL: string;
    NEXT_STRAPI_API_TOKEN: string;
    NEXT_PUBLIC_CASHFREE_APP_ID: string;
    NEXT_PUBLIC_CASHFREE_SECRET_KEY: string;
    NEXT_PUBLIC_CASHFREE_ENV: string;
  }
}
